### PR TITLE
binary_search

### PR DESCRIPTION
**Pull request by abhijithhegde**
Added Binary search

### CODE REVIEW

**Comment by geekygirl8** [comment]
Add your name and GitHub id as comments in the code.
And Star this repo and follow for the successful merge pull request.

**Comment by abhijithhegde** [comment]
Name: Abhijith Hegde
GitHub ID: abhijithhegde21

**Comment by geekygirl8** [comment]
Invalid GitHub id!!

**Comment by abhijithhegde** [comment]
> Invalid GitHub id!!
sorry just updated

**Pull request closed without merging**
