### PR TITLE
Added nearly Lucky Number and Lucky division program 

### PR DESCRIPTION
**Pull request by code4oryou**
Numbers program written in Java

### CODE REVIEW

**Comment by geekygirl8** [comment]
Add your name and github id in form of comments in code.

**Comment by geekygirl8** [comment]
Star this repo and follow for a successful merge pull request.

**Comment by code4oryou** [comment]
Name - Ayush Mandal

Github - code4oryou

**Comment by geekygirl8** [comment]
⚔️ Add link of the problem as comments in the code if contributing solution of any problems from Leetcode, GeekForGeeks, Codechef or Codeforces, etc. No need to add entire main function.
⚔️ Add the proper extension to your code file. Examples: .c, .js, .cpp , .py or .java.
⚔️ Give your file a proper name related to your program in snake_case.
⚔️ Put your files in correct folder like .cpp file in c++ folder or .py file in python folder.
⚔️ If folder is not present for your language create new with name of your programming language like C++ , Python etc
⚔️ Make repo well maintained if topic not present in which you want to contribute create new folder for it in their paricular section or language
⚔️ Please put your GitHub name and id in the file in form of comments at top to get accepted.

Please follow these rules for successful merge.

**Comment by geekygirl8** [comment]
I appreciate this but, this is an Invalid entry not as per the rules mentioned.
Closing it create a new pull request following rules for a successful merge.

**Pull request closed without merging**
